/* eslint-disable */
export enum ROLES {
	LIVE_OPS_DEFAULT = 'LiveOps Default',
	LIVE_OPS_CARE = 'Nucleus Live Ops Care',
	LIVEOPS_EXECUTIVE = 'Nucleus Liveops Executive',
}
// define your roles here
export enum EventType {
	ATTEMPTED = 'ATTEMPTED',
	STARTED = 'STARTED',
	REACHED = 'REACHED',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
	RETURNED = 'RETURNED',
}

export enum TourStatus {
	CREATED = 'CREATED',
	ASSIGNED = 'ASSIGNED',
	ATTEMPTED = 'ATTEMPTED',
	REACHED = 'REACHED',
	COMPLETED = 'COMPLETED',
	LOCKED = 'LOCKED',
	UNASSIGNED = 'UNASSIGNED',
}
export enum ORDER_FULFILLMENT_STATUSES {
	NOT_FULFILLED = 'NOT_FULFILLED',
	FULFILLED = 'FULFILLED',
	CANCELLED = 'CANCELLED',
	FULLY_DELIVERED = 'FULLY_DELIVERED',
	PARTIAL_DELIVERED = 'PARTIAL_DELIVERED',
	PARTIAL_RETURNED = 'PARTIAL_RETURNED',
	FULLY_RETURNED = 'FULLY_RETURNED',
}

export enum TOUR_ORDER_EVENT_TYPE {
	STARTED = 'STARTED',
	REACHED = 'REACHED',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
	RETURNED = 'RETURNED',
}

export enum TOUR_COLLECTION_EVENT_TYPE {
	NOT_STARTED = 'NOT_STARTED',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
}
